" Note: Skip initialization for vim-tiny or vim-small.
if 0 | endif

if has('vim_starting')
  if &compatible
    set nocompatible               " Be iMproved
  endif

  " Required:
  set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

" Required:
call neobundle#begin(expand('~/.vim/bundle/'))

" Let NeoBundle manage NeoBundle
" Required:
NeoBundleFetch 'Shougo/neobundle.vim'

" My Bundles here:
" Refer to |:NeoBundle-examples|.
" Note: You don't set neobundle setting in .gvimrc!
NeoBundle 'tpope/vim-fugitive'
NeoBundle 'thinca/vim-quickrun'
NeoBundle 'Shougo/neocomplcache'
NeoBundle 'vim-scripts/AutoComplPop'
NeoBundle 'Shougo/unite.vim'
NeoBundle 'kchmck/vim-coffee-script'
NeoBundle 'tpope/vim-haml'
NeoBundle 'oceandeep'
NeoBundle 'scrooloose/nerdtree'
NeoBundle 'alpaca-tc/alpaca_tags'
NeoBundle 'Shougo/neosnippet'
NeoBundle 'Shougo/neosnippet-snippets'
NeoBundle 'tpope/vim-rails'
NeoBundle 'basyura/unite-rails'
NeoBundle 'tpope/vim-endwise'
NeoBundle 'tomtom/tcomment_vim'
NeoBundle 'ruby-matchit'
NeoBundle 'thinca/vim-ref'
NeoBundle 'nathanaelkane/vim-indent-guides'
NeoBundle 'vim-scripts/AnsiEsc.vim'
NeoBundle 'bronson/vim-trailing-whitespace'
NeoBundle 'altercation/vim-colors-solarized'
NeoBundle 'tpope/vim-fugitive'
NeoBundle 'grep.vim'
NeoBundle 'thinca/vim-quickrun'
" color scheme
NeoBundle 'tomasr/molokai'

call neobundle#end()

" Required:
filetype plugin indent on

" If there are uninstalled bundles found on startup,
" this will conveniently prompt you to install them.
NeoBundleCheck

""" color
" visual
syntax on
colorscheme molokai
set t_Co=256
highlight Normal ctermbg=none

""" zenkaku
highlight ZenkakuSpace cterm=underline ctermfg=lightblue
match ZenkakuSpace /　/
set list
set lcs=tab:>-,trail:_

""" disp
set number
set ruler
set showmatch
set showcmd

""" edit
set autoindent
set cindent
set scrolloff=5 "fast scroll
set wrap
set whichwrap=b,s,h,l,<,>,[,]
set backspace=indent,eol,start

""" tab
set tabstop=2
set expandtab
set smarttab
set shiftwidth=2
set shiftround

""" search
set ignorecase
set smartcase
set nowrapscan
set hlsearch

""" statusline
set laststatus=2
set statusline=%<%f\ %m%r%h%w[%B/%b]
set statusline+=[%Y]%{'['.(&fenc!=''?&fenc:&enc).']['.&fileformat.']'}
set statusline+=%=%l/%L,%c%V%8P

""" keymap
nnoremap j gj
nnoremap k gk

""" encode
set enc=utf-8
set fenc=utf-8
set fileencodings=ucs-bom,utf-8,euc-jp,cp932,sjis,default,latin1

""" plugin
"" neocomplcache
let g:neocomplcache_enable_at_startup = 1
"buffer
nnoremap <silent> ,ub :<C-u>Unite buffer<CR>
"file
nnoremap <silent> ,uf :<C-u>UniteWithBufferDir -buffer-name=files file<CR>
"register
nnoremap <silent> ,ur :<C-u>Unite -buffer-name=register register<CR>
"recently
nnoremap <silent> ,um :<C-u>Unite file_mru<CR>
"ordinaly
nnoremap <silent> ,uu :<C-u>Unite buffer file_mru<CR>
"all
nnoremap <silent> ,ua :<C-u>UniteWithBufferDir -buffer-name=files buffer file_mru bookmark file<CR>

" open NERDTree when without file
if !argc()
    autocmd vimenter * NERDTree|normal gg3j
endif

"" matchit.vim
source $VIMRUNTIME/macros/matchit.vim "for ruby do end

"" vim-indent-guides
let g:indent_guides_auto_colors=0
autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd   ctermbg=235
autocmd VimEnter,Colorscheme * :hi IndentGuidesEven  ctermbg=238
let g:indent_guides_enable_on_vim_startup=1

"" vimgrep result to quickfix
autocmd QuickFixCmdPost *grep* cwindow

"" quickfix
nnoremap [q :cprevious<CR>   " next
nnoremap ]q :cnext<CR>       " previous
nnoremap [Q :<C-u>cfirst<CR> " first
nnoremap ]Q :<C-u>clast<CR>  " last
